commitlint/tests: compile test files with tsc
Enable compilation of test files by tsc for type check. Had to
set `skipLibCheck` to true because otherwise compiling test
files produces errors like this:
```
node_modules/vite-node/dist/index-WT31LSgS.d.ts:83:14 - error TS2304:
Cannot find name 'WebSocket'.
```