GitHubCI: fix auto-comment on failing PR CI
This should fix the error we're getting since we introduced
this auto-comment job:

```
Run actions/github-script@v7
/usr/bin/docker exec  13e35651b048fe2a5b8d1922ebca97c73358c10b0c6abcfe79c86075f13a9a41 sh -c "cat /etc/*release | grep ^ID"
RequestError [HttpError]: Resource not accessible by integration
    at /__w/_actions/actions/github-script/v7/dist/index.js:9537:21
Error: Unhandled error: HttpError: Resource not accessible by integration
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/tarsgate/conventions/issues/296/comments',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset, Warning',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 14 Jun 2026 22:47:47 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'issues=write; pull_requests=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'D410:2C6DC2:6428D31:17B2527A:6A2F2F93',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4976',
      'x-ratelimit-reset': '1781478676',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '24',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/issues/comments#create-an-issue-comment',
      status: '403'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/tarsgate/conventions/issues/296/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/20.20.2 (linux; x64)',
      authorization: 'bearer [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"⚠️ **CI Build Failed!**\\n\\nHey @nodefect, one or more CI jobs failed. Please check the workflow logs."}',
    request: {
      agent: [Agent],
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```